/**************** (C) COPYRIGHT 2012 青岛金仕达电子科技有限公司 ****************
* File Name          : Pin.H
* Author             : Tech-01
* Version            : V0.0.1
* Date               : 2012年3月31日
* Description        : 电路板管脚定义
*******************************************************************************/
#define	STM32F10X_MD_VL
#define SYSCLK_FREQ_24MHz  24000000
#include <stm32f10x.h>

/********  (C) COPYRIGHT 2012 青岛金仕达电子科技有限公司  **** End of File ****/
